project_id = "lkfgxtiezjnphxqlmmbm"

[functions.encrypt-data]
verify_jwt = false

[functions.decrypt-data]
verify_jwt = false

[functions.validate-coupon]
verify_jwt = false

[functions.mfa-send-otp]
verify_jwt = false

[functions.mfa-verify-otp]
verify_jwt = false

[functions.mfa-check-device]
verify_jwt = false

[functions.send-consent-email]
verify_jwt = false

[functions.send-approval-email]
verify_jwt = false
